POST http://localhost:3000/posts HTTP/1.1
content-type: application/json

{
    "title": "fifth post tile",
    "body": "body of fifth post Wed, 21 Oct 2015 18:27:50 GMT"
}

###

GET http://localhost:3000/posts HTTP/1.1

###

GET http://localhost:3000/posts/6 HTTP/1.1

###

PUT http://localhost:3000/posts/6 HTTP/1.1
content-type: application/json

{
    "title": "6th post udpated",
    "body": "updated 6th post"
}

###

DELETE http://localhost:3000/posts/6 HTTP/1.1

